# Generated by Django 5.1.4 on 2024-12-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='additional_info',
            new_name='additionalInfo',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='is_public',
            new_name='isPublic',
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photos',
            field=models.ImageField(upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
