# Generated by Django 5.1.5 on 2025-01-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pet_animal_id_pet_features_pet_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='photos',
        ),
    ]
