# Generated by Django 5.1.5 on 2025-01-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_pet_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='additionalInfo',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
