# Generated by Django 5.1.5 on 2025-01-25 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pet_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='additionalInfo',
            field=models.JSONField(default=dict),
        ),
    ]
