# Generated by Django 5.1.5 on 2025-01-25 18:00

import accounts.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pet_additionalinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-registered_at']},
        ),
        migrations.AlterField(
            model_name='pet',
            name='additionalInfo',
            field=models.JSONField(default=dict, validators=[accounts.models.validate_json_dict]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_id',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Breed can only contain letters and spaces', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Wild', 'Wild'), ('Exotic', 'Exotic'), ('Farm', 'Farm')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='features',
            field=models.JSONField(default=list, validators=[accounts.models.validate_json_list]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='images',
            field=models.JSONField(default=list, validators=[accounts.models.validate_json_list]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Name can only contain letters, numbers, spaces, apostrophes, and hyphens', regex="^[a-zA-Z0-9 \\'-]+$")]),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pet',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(message='Type can only contain letters and spaces', regex='^[a-zA-Z ]+$')]),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['animal_id'], name='accounts_pe_animal__b0fbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['owner'], name='accounts_pe_owner_i_d73c92_idx'),
        ),
    ]
