# Generated by Django 5.1.5 on 2025-01-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_pet_options_alter_pet_additionalinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_id',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Wild', 'Wild'), ('Poultry', 'Poultry'), ('Livestock', 'Livestock')], max_length=100),
        ),
    ]
